---
openapi: 3.0.1
components:
  securitySchemes:
    admin:
      type: apiKey
      in: cookie
      name: _api_session
info:
  title: API V1
  version: v1
paths:
  "/api/admin/accounting_accounts":
    get:
      summary: Retrieves All Accounting Accounts
      tags:
      - AccountingAccounts
      parameters:
      - in: cookie
        required: true
        name: locale
        schema:
          type: string
      responses:
        '200':
          description: Fetch Accountings Accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  buy:
                    type: array
                    items:
                      type: object
                  sell:
                    type: array
                    items:
                      type: object
                  inv:
                    type: array
                    items:
                      type: object
                required:
                - buy
                - sell
                - inv
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
    post:
      summary: Create New Account
      tags:
      - AccountingAccounts
      parameters: []
      responses:
        '201':
          description: Create Accounting Account Successfuly
          content:
            application/json:
              schema:
                type: object
                properties:
                  account:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      category:
                        type: string
                      subcategory:
                        type: string
                      company_id:
                        type: integer
                      user_id:
                        type: integer
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                  message:
                    type: string
                  csrf:
                    type: string
                required:
                - csrf
                - account
                - message
        '200':
          description: Create Accounting Account Unsuccessfuly
          content:
            application/json:
              schema:
                type: object
                properties:
                  account:
                    type: object
                    properties:
                      id:
                        type: integer
                        nullable: true
                      name:
                        type: string
                        nullable: true
                      category:
                        type: string
                        nullable: true
                      subcategory:
                        type: string
                        nullable: true
                      company_id:
                        type: integer
                        nullable: true
                      user_id:
                        type: integer
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                        nullable: true
                      updated_at:
                        type: string
                        format: date-time
                        nullable: true
                  csrf:
                    type: string
                  message:
                    type: object
                required:
                - csrf
                - account
                - message
        '401':
          description: User not supported
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - accounting_account[name]
              - accounting_account[category]
              - accounting_account[subcategory]
              - authenticity_token
              properties:
                accounting_account[name]:
                  type: string
                  description: Name of New Category
                  example: General Income
                accounting_account[category]:
                  type: string
                  description: Category Should be inv, in, or out
                  example: in
                accounting_account[subcategory]:
                  type: string
                  description: SubCategory refer to the group which the category will
                    belong to
                  example: Income
                authenticity_token:
                  type: string
                  description: CSRF Token Protected
  "/api/admin/articles_groups":
    get:
      summary: Retrieves All Articles Groups
      tags:
      - ArticlesGroups
      parameters:
      - in: cookie
        required: true
        name: locale
        schema:
          type: string
      responses:
        '200':
          description: Fetch Articles Groups
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '401':
          description: Unauthorized User
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
    post:
      summary: Create New Article Groups
      tags:
      - ArticlesGroups
      parameters: []
      responses:
        '201':
          description: Create Article Group Successfuly
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      company_id:
                        type: integer
                      user_id:
                        type: integer
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                  message:
                    type: string
                  csrf:
                    type: string
                required:
                - csrf
                - group
                - message
        '200':
          description: Create Article Group Unsuccessfuly
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    type: object
                    properties:
                      id:
                        type: integer
                        nullable: true
                      name:
                        type: string
                        nullable: true
                      company_id:
                        type: integer
                        nullable: true
                      user_id:
                        type: integer
                        nullable: true
                      created_at:
                        type: string
                        format: date-time
                        nullable: true
                      updated_at:
                        type: string
                        format: date-time
                        nullable: true
                  csrf:
                    type: string
                  message:
                    type: object
                required:
                - csrf
                - account
                - message
        '401':
          description: User not supported
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - articles_group[name]
              - authenticity_token
              properties:
                articles_group[name]:
                  type: string
                  description: Name of New Group
                  example: Fruits
                authenticity_token:
                  type: string
                  description: CSRF Token Protected
  "/api/admin/auth/admins/sign_in":
    get:
      summary: Retrieves CSRF Token And User
      tags:
      - Sessions
      parameters:
      - in: cookie
        required: true
        name: locale
        schema:
          type: string
      responses:
        '200':
          description: Fetch CSRF Token
          content:
            application/json:
              schema:
                type: object
                properties:
                  locale:
                    type: string
                    default: es
                  csrf:
                    type: object
                    properties:
                      resource_name:
                        type: string
                      authToken:
                        type: string
                required:
                - csrf
        '202':
          description: Fetch CSRF Token and User if Already Login
          content:
            application/json:
              schema:
                type: object
                properties:
                  locale:
                    type: string
                    default: es
                  csrf:
                    type: object
                    properties:
                      resource_name:
                        type: string
                      authToken:
                        type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      firstname:
                        type: string
                      lastname:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      company_id:
                        type: integer
                      user_id:
                        type: integer
                      created_at:
                        type: string
                        format: date-time
                      updated_at:
                        type: string
                        format: date-time
                required:
                - csrf
                - user
    post:
      summary: Login User
      tags:
      - Sessions
      parameters: []
      responses:
        '201':
          description: Login User
          content: {}
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - api_admin_auth_admin[login]
              - api_admin_auth_admin[password]
              properties:
                authenticity_token:
                  type: string
                api_admin_auth_admin[login]:
                  type: string
                api_admin_auth_admin[password]:
                  type: password
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
