// I18N
export const GET_I18N = 'GET_I18N';

// LOCALE
export const GET_LOCALE = 'GET_LOCALE';

// STORE DATA
export const GET_STORE_DATA = 'GET_STORE_DATA';

// FETCHING
export const START_FETCHING = 'START_FETCHING';
export const FINISH_FETCHING = 'FINISH_FETCHING';

// CSRF PROTECTION
export const GET_CSRF_PROTECTION = 'GET_CSRF_PROTECTION';
export const GET_CSRF_PROTECTION_LOGGED_IN = 'GET_CSRF_PROTECTION_LOGGED_IN';
export const RENEW_CSRF_PROTECTION = 'RENEW_CSRF_PROTECTION';

// USER ACTION
export const SIGN_IN_USER_SUCCESSFULY = 'SIGN_IN_USER_SUCCESSFULY';
export const SIGN_IN_USER_ERROR = 'SIGN_IN_USER_ERROR';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

// ACCOUNTING ACCOUNTS
export const GET_ACCOUNTING_ACOUNTS = 'GET_ACCOUNTING_ACOUNTS';
export const CREATE_SELL_ACCOUNTING_ACCOUNTS = 'CREATE_SELL_ACCOUNTING_ACCOUNTS';
export const CREATE_BUY_ACCOUNTING_ACCOUNTS = 'CREATE_BUY_ACCOUNTING_ACCOUNTS';
export const CREATE_INV_ACCOUNTING_ACCOUNTS = 'CREATE_INV_ACCOUNTING_ACCOUNTS';

// ARTICLES GROUPS
export const GET_ARTICLES_GROUPS = 'GET_ARTICLES_GROUPS';
export const CREATE_ARTICLES_GROUP = 'CREATE_ARTICLES_GROUP';

// TAXES
export const GET_TAXES = 'GET_TAXES';

// EXCHANGES
export const CREATE_EXCHANGE = 'CREATE_EXCHANGE';

// ARTICLE
export const CREATE_ARTICLE = 'CREATE_ARTICLE';

// LOAD TOAST MESSAGE
export const TOAST_MESSAGE = 'TOAST_MESSAGE';

export const FORCE_RESET = 'FORCE_RESET';
