// I18N
export const GET_I18N = 'GET_I18N';

// CSRF PROTECTION
export const GET_CSRF_PROTECTION = 'GET_CSRF_PROTECTION';
export const GET_CSRF_PROTECTION_LOGGED_IN = 'GET_CSRF_PROTECTION_LOGGED_IN';

// USER ACTION
export const SIGN_IN_USER_SUCCESSFULY = 'SIGN_IN_USER_SUCCESSFULY';
export const SIGN_IN_USER_ERROR = 'SIGN_IN_USER_ERROR';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
