// I18N
export const GET_I18N = 'GET_I18N';

// Fetching
export const START_FETCHING = 'START_FETCHING';
export const FINISH_FETCHING = 'FINISH_FETCHING';

// CSRF PROTECTION
export const GET_CSRF_PROTECTION = 'GET_CSRF_PROTECTION';
export const GET_CSRF_PROTECTION_LOGGED_IN = 'GET_CSRF_PROTECTION_LOGGED_IN';
export const RENEW_CSRF_PROTECTION = 'RENEW_CSRF_PROTECTION';

// USER ACTION
export const SIGN_IN_USER_SUCCESSFULY = 'SIGN_IN_USER_SUCCESSFULY';
export const SIGN_IN_USER_ERROR = 'SIGN_IN_USER_ERROR';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

// ACCOUNTING ACCOUNTS
export const GET_ACCOUNTING_ACOUNTS = 'GET_ACCOUNTING_ACOUNTS';

// ARTICLE GROUPS
export const GET_ARTICLES_GROUPS = 'GET_ARTICLES_GROUPS';
export const CREATE_ARTICLES_GROUP = 'CREATE_ARTICLES_GROUP';
