name: Api CI

on:
  push:
#    paths: 'api/**'

jobs:
  RSpec:
    name: RSpec in Api
    runs-on: ubuntu-latest
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }} 
      api-dir: ./api 

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby

    - name: Build Api
      run: |
        docker-compose -f docker-compose.linux.yml build api
    - name: Create Database
      run: |
        docker-compose run -e RAILS_ENV=test -e RAILS_MASTER_KEY=${{env.RAILS_MASTER_KEY}} api rails db:setup
    - name: Run Test
      run: |
        docker-compose run -e RAILS_ENV=test -e RAILS_MASTER_KEY=${{env.RAILS_MASTER_KEY}} -T api rspec

  Rubocop:
    name: Rubocop in Api
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Install Rubocop
      run: |
          gem install rubocop

    - name: Run Tests
      working-directory: ${{env.api-dir}}
      run: |
        rubocop
