name: Client CI
on:
  push:
    paths: 'client/**'
jobs:
  Jest:
    env:
      client-dir: ./client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12'
      - name: Install yarn
        run: |
          npm install --global yarn
      - name: Install Dependencies
        working-directory: ${{env.client-dir}}
        run: |
          yarn
      - name: Run Jest
        working-directory: ${{env.client-dir}}
        run: |
          yarn test

  ESLint:
    env:
      client-dir: ./client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12'
      - name: Install ESLint
        run: |
          npm i -g eslint
      - name: Install yarn
        run: |
          npm install --global yarn
      - name: Install Dependencies
        working-directory: ${{env.client-dir}}
        run: |
          yarn
      - name: Run Eslint
        working-directory: ${{env.client-dir}}
        run: |
          eslint . --ext .js,.jsx,.ts,.tsx