name: corporate CI

on:
  push:

jobs:
  Jest:
    env:
      corporate-dir: ./corporate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3'
      - name: Install yarn
        run: |
          npm install --global yarn
      - name: Install Dependencies
        working-directory: ${{env.corporate-dir}}
        run: |
          yarn
      - name: Run Jest
        working-directory: ${{env.corporate-dir}}
        run: |
          yarn test
