name: ESLint

on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3'
      - name: Install ESLint
        run: |
          npm i -g eslint
      - name: Install yarn
        run: |
          npm install --global yarn
      - name: Install Dependencies
        working-directory: ${{env.client-dir}}
        run: |
          yarn
      - name: Run Eslint
        working-directory: ${{env.client-dir}}
        run: |
          eslint . --ext .js,.jsx,.ts,.tsx
